version: '3.8'

services:
  postgres:
    container_name: forum_nest_cleanarq
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest_clean
      PGDATA: /data/postgres
    volumes:
      - .data/pg:/data/postgres
  
  cache:
    container_name: forum_nest_cleanarq_cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - .data/redis:/data